# -*- coding: utf-8 -*-
"""DCEE_v2_Colab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LBneGFyvkLvpjn3yD3hMXM7Zr8OtZDzb

# ⚡ DCEE v2 — Delta-Compressed Embedding Engine (Vectorised GPU)

## What changed from v1

| | v1 | v2 |
|---|---|---|
| Per-query Python loop | ✅ 50,000 iterations | ❌ eliminated |
| GPU kernel launches | thousands (tiny) | 3–4 (large) |
| Reconstruction | one vector at a time | entire cluster via `cumsum` |
| Score computation | loop + tiny dot products | single `(N,dim) @ (dim,)` matmul |
| Expected latency | ~3000 ms | **~5–30 ms** |

**Set Runtime → T4 GPU before running!**
"""

# Cell 1 — Install
!pip install -q cupy-cuda12x scikit-learn tqdm
print('✅ done')

# Cell 2 — GPU check
!nvidia-smi --query-gpu=name,memory.total,memory.free --format=csv,noheader

# Cell 3 — Full DCEE v2 implementation
"""
v1 bottleneck:  Python loop per vector → thousands of tiny GPU kernel launches
v2 fix:         Store entire cluster as ONE (N, dim) GPU tensor
                cumsum(delta_matrix) reconstructs all N vectors in 1 kernel
                (N,dim) @ (dim,) scores all vectors in 1 matmul
"""

import os, time, struct, pickle, warnings
import numpy as np
from dataclasses import dataclass
from typing import List, Tuple, Optional
warnings.filterwarnings('ignore')

try:
    import cupy as cp
    GPU_AVAILABLE = cp.cuda.is_available()
except ImportError:
    GPU_AVAILABLE = False

if GPU_AVAILABLE:
    xp = cp
    print(f'✅ GPU: {cp.cuda.runtime.getDeviceProperties(0)["name"].decode()}')
else:
    xp = np
    print('ℹ CPU mode')

from sklearn.cluster import MiniBatchKMeans
from sklearn.preprocessing import normalize
from tqdm.auto import tqdm

def to_cpu(a): return cp.asnumpy(a) if GPU_AVAILABLE and isinstance(a, cp.ndarray) else np.asarray(a)
def to_gpu(a): return cp.array(a, dtype=cp.float32) if GPU_AVAILABLE else np.asarray(a, dtype=np.float32)


# ─── Config ────────────────────────────────────────────────────────────────
@dataclass
class DCEEConfig:
    dim:            int   = 128
    n_clusters:     int   = 64
    keyframe_every: int   = 16
    quantization:   str   = 'int8'   # 'float32' | 'float16' | 'int8'
    top_k_refine:   int   = 20
    n_probe:        int   = 8
    batch_size:     int   = 4096


# ─── Data structures ────────────────────────────────────────────────────────
@dataclass
class ClusterBlockV2:
    cluster_id:     int
    global_indices: np.ndarray   # (N,) int32
    delta_q:        np.ndarray   # (N, dim) quantised — row 0 = zeros
    scales:         np.ndarray   # (N,) float32
    kf_mask:        np.ndarray   # (N,) bool — True = keyframe reset row
    kf_values:      np.ndarray   # (N, dim) float32 — per-row keyframe
    _gpu_reconstructed: object = None

@dataclass
class DCEEIndex:
    config:          DCEEConfig
    clusters:        list
    keyframe_matrix: np.ndarray


# ─── Preprocessing ──────────────────────────────────────────────────────────
class EmbeddingPreprocessor:
    def __init__(self, cfg): self.cfg = cfg

    def cluster(self, emb):
        print(f'\n📦 Clustering {len(emb):,} embeddings → {self.cfg.n_clusters} clusters …')
        km = MiniBatchKMeans(n_clusters=self.cfg.n_clusters, batch_size=max(4096, self.cfg.batch_size), n_init=3, random_state=42)
        labels = km.fit_predict(normalize(emb))
        groups = [[] for _ in range(self.cfg.n_clusters)]
        for i, l in enumerate(labels): groups[l].append(i)
        sizes = [len(g) for g in groups if g]
        print(f'   sizes — min:{min(sizes)}  max:{max(sizes)}  avg:{np.mean(sizes):.0f}')
        return groups

    def greedy_order(self, vecs):
        n = len(vecs)
        if n <= 2: return list(range(n))
        visited = np.zeros(n, bool); order = [0]; visited[0] = True; cur = vecs[0]
        for _ in range(n-1):
            d = np.sum((vecs - cur)**2, axis=1); d[visited] = np.inf
            nxt = int(np.argmin(d)); order.append(nxt); visited[nxt] = True; cur = vecs[nxt]
        return order


# ─── Vectorised Delta Encoder ────────────────────────────────────────────────
class VectorisedDeltaEncoder:
    def __init__(self, cfg): self.cfg = cfg

    def encode_cluster(self, vecs, global_ids):
        N, D = vecs.shape; kfe = self.cfg.keyframe_every
        delta_f32 = np.zeros((N, D), np.float32)
        kf_mask   = np.zeros(N, bool)
        kf_values = np.zeros((N, D), np.float32)
        cur_kf = vecs[0].copy()
        for i in range(N):
            if i % kfe == 0:
                kf_mask[i] = True; cur_kf = vecs[i].copy(); delta_f32[i] = 0.0
            else:
                delta_f32[i] = vecs[i] - vecs[i-1]
            kf_values[i] = cur_kf

        q = self.cfg.quantization
        if q == 'int8':
            scales  = np.max(np.abs(delta_f32), axis=1) / 127.0 + 1e-9
            delta_q = np.clip(np.round(delta_f32 / scales[:,None]), -127, 127).astype(np.int8)
        elif q == 'float16':
            delta_q = delta_f32.astype(np.float16); scales = np.ones(N, np.float32)
        else:
            delta_q = delta_f32; scales = np.ones(N, np.float32)

        return ClusterBlockV2(
            cluster_id=0, global_indices=np.array(global_ids, np.int32),
            delta_q=delta_q, scales=scales.astype(np.float32),
            kf_mask=kf_mask, kf_values=kf_values,
        )

    def decode_cluster_gpu(self, block):
        """THE CORE FIX: reconstruct all N vectors in 3 GPU ops."""
        if block._gpu_reconstructed is not None:
            return block._gpu_reconstructed
        N, D = block.delta_q.shape

        # 1. Dequantise → GPU
        if self.cfg.quantization == 'int8':
            delta_gpu = xp.array(block.delta_q, xp.float32) * xp.array(block.scales, xp.float32)[:,None]
        else:
            delta_gpu = xp.array(block.delta_q, xp.float32)

        # Zero reset rows so cumsum stays clean
        delta_gpu[xp.array(block.kf_mask)] = 0.0

        # 2. One cumsum kernel
        cumsum_gpu = xp.cumsum(delta_gpu, axis=0)

        # 3. Subtract segment baseline (Python loop over K keyframes, not N vectors)
        kf_indices = np.where(block.kf_mask)[0]
        kf_cumsum  = cumsum_gpu[xp.array(kf_indices)]  # (K, D)
        baseline   = xp.zeros((N, D), xp.float32)
        for seg_i, kf_pos in enumerate(kf_indices):
            nxt = kf_indices[seg_i+1] if seg_i+1 < len(kf_indices) else N
            baseline[kf_pos:nxt] = kf_cumsum[seg_i]

        # 4. Add keyframe values
        recon = xp.array(block.kf_values, xp.float32) + (cumsum_gpu - baseline)
        block._gpu_reconstructed = recon
        return recon


# ─── GPU Query Engine v2 ─────────────────────────────────────────────────────
class GPUQueryEngineV2:
    def __init__(self, index, encoder):
        self.index = index; self.encoder = encoder; self.cfg = index.config
        kfm = index.keyframe_matrix.astype(np.float32)
        self.kf_gpu = to_gpu(kfm / (np.linalg.norm(kfm, axis=1, keepdims=True) + 1e-9))
        print('⚡ Pre-building GPU cluster tensors …', end=' ', flush=True)
        t0 = time.time()
        for b in index.clusters: encoder.decode_cluster_gpu(b)
        print(f'done in {time.time()-t0:.2f}s')

    def search(self, query, top_k=5):
        q_gpu  = to_gpu(query)
        q_norm = q_gpu / (xp.linalg.norm(q_gpu) + 1e-9)

        # Phase 1: score all keyframes — 1 matmul
        kf_scores = to_cpu(self.kf_gpu @ q_norm)
        n_probe   = min(self.cfg.n_probe, len(self.index.clusters))
        top_cids  = np.argpartition(kf_scores, -n_probe)[-n_probe:]
        top_cids  = top_cids[np.argsort(kf_scores[top_cids])[::-1]]

        # Phase 2: score vectors in top clusters — 1 matmul each
        all_scores, all_gidx = [], []
        for cid in top_cids:
            block = self.index.clusters[cid]
            recon = block._gpu_reconstructed
            norms = xp.linalg.norm(recon, axis=1, keepdims=True) + 1e-9
            scores = to_cpu((recon / norms) @ q_norm)
            all_scores.append(scores); all_gidx.append(block.global_indices)

        # Phase 3: pick top-K candidates
        cs = np.concatenate(all_scores); cg = np.concatenate(all_gidx)
        rk = min(self.cfg.top_k_refine, len(cs))
        top_li = np.argpartition(cs, -rk)[-rk:]
        top_li = top_li[np.argsort(cs[top_li])[::-1]]

        # Phase 4: full-precision refine
        q_cpu = to_cpu(q_norm)
        refined = []
        for li in top_li:
            gidx = int(cg[li])
            cid_r, local_r = self._rev_map[gidx]
            vec = to_cpu(self.index.clusters[cid_r]._gpu_reconstructed[local_r])
            score = float(np.dot(vec, q_cpu) / (np.linalg.norm(vec) + 1e-9))
            refined.append((gidx, score))
        refined.sort(key=lambda x: -x[1])
        return refined[:top_k]

    def _build_reverse_map(self):
        self._rev_map = {}
        for cid, b in enumerate(self.index.clusters):
            for li, gi in enumerate(b.global_indices): self._rev_map[int(gi)] = (cid, li)


# ─── Storage ────────────────────────────────────────────────────────────────
MAGIC, VERSION = b'DCE2', 2

def save_index(index, path):
    with open(path, 'wb') as f:
        cfg = index.config
        f.write(MAGIC); f.write(struct.pack('B', VERSION))
        f.write(struct.pack('IIIII', cfg.dim, cfg.n_clusters, cfg.keyframe_every, cfg.top_k_refine, cfg.n_probe))
        f.write(struct.pack('B', ['float32','float16','int8'].index(cfg.quantization)))
        f.write(index.keyframe_matrix.astype(np.float32).tobytes())
        for b in index.clusters:
            N = len(b.global_indices)
            f.write(struct.pack('II', b.cluster_id, N))
            f.write(b.global_indices.astype(np.int32).tobytes())
            f.write(b.kf_mask.astype(np.uint8).tobytes())
            f.write(b.kf_values.astype(np.float32).tobytes())
            f.write(b.scales.astype(np.float32).tobytes())
            dt = {'float32':0,'float16':1,'int8':2}[cfg.quantization]
            f.write(struct.pack('B', dt)); f.write(b.delta_q.tobytes())
    print(f'💾 Saved → {path}  ({os.path.getsize(path)/1e6:.2f} MB)')

def load_index(path):
    with open(path, 'rb') as f:
        assert f.read(4) == MAGIC; f.read(1)
        dim,nc,kfe,topk,nprobe = struct.unpack('IIIII', f.read(20))
        qm = ['float32','float16','int8'][struct.unpack('B', f.read(1))[0]]
        cfg = DCEEConfig(dim=dim,n_clusters=nc,keyframe_every=kfe,quantization=qm,top_k_refine=topk,n_probe=nprobe)
        kfm = np.frombuffer(f.read(nc*dim*4), np.float32).reshape(nc,dim).copy()
        clusters = []
        for _ in range(nc):
            cid,N = struct.unpack('II', f.read(8))
            gidx    = np.frombuffer(f.read(N*4),    np.int32).copy()
            kf_mask = np.frombuffer(f.read(N),       np.uint8).astype(bool).copy()
            kf_vals = np.frombuffer(f.read(N*dim*4), np.float32).reshape(N,dim).copy()
            scales  = np.frombuffer(f.read(N*4),     np.float32).copy()
            dt_tag  = struct.unpack('B', f.read(1))[0]
            dt = [np.float32, np.float16, np.int8][dt_tag]
            delta_q = np.frombuffer(f.read(N*dim*np.dtype(dt).itemsize), dt).reshape(N,dim).copy()
            clusters.append(ClusterBlockV2(cid,gidx,delta_q,scales,kf_mask,kf_vals))
    total = sum(len(b.global_indices) for b in clusters)
    print(f'📂 Loaded → {path}  ({total:,} vectors, {nc} clusters)')
    return DCEEIndex(cfg, clusters, kfm)


# ─── High-level Engine ──────────────────────────────────────────────────────
class DCEEEngine:
    def __init__(self, cfg):
        self.cfg = cfg
        self.pre = EmbeddingPreprocessor(cfg)
        self.enc = VectorisedDeltaEncoder(cfg)
        self.index = None; self.qe = None

    def build(self, emb):
        emb = emb.astype(np.float32); N = len(emb)
        t0 = time.time()
        groups = self.pre.cluster(emb)
        print(f'\n🔧 Delta-encoding {self.cfg.n_clusters} clusters …')
        clusters, kf_list = [], []
        for cid, gids in enumerate(tqdm(groups, desc='Encoding')):
            if not gids: continue
            vecs = emb[gids]; order = self.pre.greedy_order(vecs)
            vecs_o = vecs[order]; gids_o = [gids[o] for o in order]
            block = self.enc.encode_cluster(vecs_o, gids_o)
            block.cluster_id = cid; clusters.append(block); kf_list.append(vecs_o[0])
        kfm = np.stack(kf_list)
        self.index = DCEEIndex(self.cfg, clusters, kfm)
        self.qe = GPUQueryEngineV2(self.index, self.enc)
        self.qe._build_reverse_map()
        bpv = {'float32':4,'float16':2,'int8':1}.get(self.cfg.quantization,4)
        raw = N*self.cfg.dim*4/1e6; comp = N*self.cfg.dim*bpv/1e6
        print(f"\n{'═'*46}")
        print(f'  Vectors     : {N:>10,}')
        print(f'  Raw         : {raw:>9.2f} MB')
        print(f'  Compressed  : {comp:>9.2f} MB  ({raw/comp:.1f}×)')
        print(f'  Build time  : {time.time()-t0:>9.2f} s')
        print(f"{'═'*46}\n")

    def search(self, query, top_k=5):
        assert self.qe, 'Call build() first'
        return self.qe.search(query, top_k)

    def save(self, path): save_index(self.index, path)

    def load(self, path):
        self.index = load_index(path); self.cfg = self.index.config
        self.enc = VectorisedDeltaEncoder(self.cfg)
        self.qe = GPUQueryEngineV2(self.index, self.enc)
        self.qe._build_reverse_map()

print('✅ DCEE v2 loaded!')

# Cell 4 — Generate correlated data
DIM = 128; N = 50_000; NC = 64
rng = np.random.default_rng(42)
topics = rng.standard_normal((NC, DIM)).astype(np.float32)
topics = topics / np.linalg.norm(topics, axis=1, keepdims=True)
labels = rng.integers(0, NC, N)
noise  = rng.standard_normal((N, DIM)).astype(np.float32) * 0.15
emb    = topics[labels] + noise
emb    = emb / np.linalg.norm(emb, axis=1, keepdims=True)
print(f'Embeddings: {emb.shape}')

# Cell 5 — Build index
cfg = DCEEConfig(
    dim=DIM, n_clusters=NC,
    keyframe_every=16,
    quantization='int8',
    top_k_refine=20,
    n_probe=8,
)
engine = DCEEEngine(cfg)
engine.build(emb)

# Cell 6 — Latency benchmark (200 queries)
TOP_K = 5; N_Q = 200
qids = rng.integers(0, N, N_Q)

# warm-up
for qid in qids[:5]: engine.search(emb[qid], top_k=TOP_K)

lats, hits = [], 0
for qid in tqdm(qids, desc='Querying'):
    t0 = time.perf_counter()
    res = engine.search(emb[qid], top_k=TOP_K)
    lats.append((time.perf_counter()-t0)*1000)
    if int(qid) in [r for r,_ in res]: hits += 1

print(f"""
─────────────────────────────────────
  Recall@{TOP_K}    : {hits/N_Q*100:.1f}%
  Latency p50 : {np.percentile(lats,50):.2f} ms
  Latency p95 : {np.percentile(lats,95):.2f} ms
  Latency p99 : {np.percentile(lats,99):.2f} ms
  Throughput  : {1000/np.median(lats):.0f} QPS
─────────────────────────────────────""")

# Cell 7 — n_probe sweep: latency vs recall tradeoff
print(f'  {"n_probe":>8} {"Recall%":>9} {"P50ms":>8} {"QPS":>8}')
print('  ' + '─'*38)
for np_ in [2, 4, 8, 16, 32, NC]:
    cfg_p = DCEEConfig(dim=DIM, n_clusters=NC, keyframe_every=16,
                       quantization='int8', top_k_refine=20, n_probe=np_)
    eng_p = DCEEEngine(cfg_p); eng_p.build(emb)
    ls, rc = [], 0
    for qid in qids[:100]:
        t1 = time.perf_counter(); res = eng_p.search(emb[qid], top_k=TOP_K)
        ls.append((time.perf_counter()-t1)*1000)
        if int(qid) in [r for r,_ in res]: rc += 1
    p50 = np.median(ls)
    print(f'  {np_:>8} {rc/100*100:>8.1f}% {p50:>7.2f} {1000/p50:>7.0f}')

# Cell 8 — Quantization comparison
print(f'  {"Mode":<10} {"Build(s)":>9} {"Recall%":>9} {"P50ms":>8} {"MB":>7}')
print('  ' + '─'*46)
for qm in ['float32', 'float16', 'int8']:
    cfg_q = DCEEConfig(dim=DIM, n_clusters=NC, keyframe_every=16,
                       quantization=qm, top_k_refine=20, n_probe=8)
    eng_q = DCEEEngine(cfg_q)
    t0 = time.time(); eng_q.build(emb); bt = time.time()-t0
    ls, rc = [], 0
    for qid in qids[:100]:
        t1 = time.perf_counter(); res = eng_q.search(emb[qid], top_k=TOP_K)
        ls.append((time.perf_counter()-t1)*1000)
        if int(qid) in [r for r,_ in res]: rc += 1
    bpv = {'float32':4,'float16':2,'int8':1}[qm]
    print(f'  {qm:<10} {bt:>9.2f} {rc/100*100:>8.1f}% {np.median(ls):>7.2f} {N*DIM*bpv/1e6:>7.2f}')

# Cell 9 — Save and reload
engine.save('/tmp/dcee_v2.dce2')
engine3 = DCEEEngine(cfg)
engine3.load('/tmp/dcee_v2.dce2')
# Verify
r = engine3.search(emb[0], top_k=3)
print('Sanity check:', r)

"""## Plug in your own embeddings

```python
cfg = DCEEConfig(
    dim    = your_embeddings.shape[1],
    n_clusters    = 128,          # rule of thumb: sqrt(N)
    keyframe_every= 16,
    quantization  = 'int8',
    n_probe       = 8,            # increase for better recall, increase latency
    top_k_refine  = 20,
)
engine = DCEEEngine(cfg)
engine.build(your_embeddings)   # (N, dim) float32
results = engine.search(query, top_k=10)
# → [(global_index, cosine_similarity), ...]
```

**Tuning guide:**
- `n_probe` ↑ → recall ↑, latency ↑ (linear)
- `keyframe_every` ↑ → recall ↑ (less error accumulation), compression same
- `quantization='int8'` → 4× compression, ~0% recall loss on correlated data
- `n_clusters ≈ sqrt(N)` is a reliable starting point
"""